### ISSUE TITLE
The time of duration for running pose_transfer_test.py

### ISSUE THREAD

**Issue by CHNxindong** [YanzuoLu/CFLD#14]
Thanks for your great work! 
When I run the pose_transfer_test.py in single RTX 4090, it needs nearly 4 hours. I want to know whether this time of duration is normal? 
![image](https://github.com/YanzuoLu/CFLD/assets/20262070/0eed42e4-77db-4532-bfd3-edcd1aaab098)

**Comment by YanzuoLu** [comment]
It's a normal speed since the denoising would take 50 steps by default.
Thanks for your attention to our work : )
