### ISSUE TITLE
Inference image resolution 256x176

### ISSUE THREAD

**Issue by triton99** [YanzuoLu/CFLD#18]
Hi @YanzuoLu , Thanks for sharing this great work!

I want to run the inference for the image resolution 256x176. Could you share the instruction and the config file for your model? In the playground.ipynb, the latent output size is 64x64, and the output of the value decoder is 512x512 now.

Thank you.

**Comment by YanzuoLu** [comment]
To use pre-trained SD15 we always have only one model to generate 512x512. 
Evaluation is achieved through resizing.
Hope this helps.
