### ISSUE TITLE
Classifier-free Guidance for training

### ISSUE THREAD

**Issue by CHNxindong** [YanzuoLu/CFLD#19]
Hi authors. Thanks again for your great work! I have noticed that your methodology incorporates the use of classifier-free guidance both during the training and testing phases. The configuration parameter 'MODEL.U_COND_DOWN_BLOCK_GUIDANCE' has been set to False, which seemingly implies that the model has not undergone training in an unconditional pose setting.  I would greatly appreciate clarification on your approach in this regard. 

![image](https://github.com/YanzuoLu/CFLD/assets/20262070/57fd7a32-1dee-4154-9191-578bbdfc3f08)

![image](https://github.com/YanzuoLu/CFLD/assets/20262070/a077d630-3626-4a37-90fd-a5da5447220a)

**Comment by YanzuoLu** [comment]
This should be set to True. 
But in fact, there is not much difference whether these two are enabled or not in the experiments we found.
Hope this can help.
