### ISSUE TITLE
Question about the convolution layer channel in the CFLD program

### ISSUE THREAD

**Issue by lyx-JuneSnow** [YanzuoLu/CFLD#24]
[error.pdf](https://github.com/user-attachments/files/15579639/error.pdf)
Hello, I just sent you an email. I hope you can forgive my mistake. The pdf file is the complete call stack information. Please check it and help me solve this problem. Thank you very much!

**Comment by YanzuoLu** [comment]
Hi, @lyx-JuneSnow 
I have never met this before. Please check the shape of input pred and gt images.
It happened within lpips model.

**Comment by lyx-JuneSnow** [comment]
OK. I'll continue to review the code and debug it, thanks.
