### ISSUE TITLE
 Reproduce question on test split 

### ISSUE THREAD

**Issue by RuijieH** [YanzuoLu/CFLD#27]
Hi.
When i use the checkpoint offered and run the pose_transfer_test.sh using the default hyperparam, I can't generate the same picture you offered in README, also results in poor performance in metric compared to the images you offered.
So i want to know are there some changes of hyperparams when you generate results images compared to the default hyperparam

**Comment by zcai0612** [comment]
Same as https://github.com/YanzuoLu/CFLD/issues/27#issue-2369496749

**Comment by zcai0612** [comment]
Sharing the same problem

**Comment by YanzuoLu** [comment]
Hi, @RuijieH
To compare with the non-open-sourced ICCV 2023 paper PoCoLD and achieve higher
 quantitative metrics, we have earlystop strategy during training and the released checkpoints are simply from the final epoch just for demonstration.
You could try retrain for fully reproduce and conduct thorough experiments on intermediate states.
Good luck！
