### ISSUE TITLE
torch.cuda.is_available() should be True but is False.

### ISSUE THREAD

**Issue by bbing32475** [YanzuoLu/CFLD#34]
Hello, I encountered the following error after setting up the environment and starting the training：ValueError: torch.cuda.is_available() should be True but is False. xformers' memory efficient attention is only available for GPU

**Comment by YanzuoLu** [comment]
Please find your GPUs and install drivers.

**Comment by bbing32475** [comment]
I can find my GPU when running other projects, but I get this error when running this project.
