### ISSUE TITLE
About the precision of compared results

### ISSUE THREAD

**Issue by CHNxindong** [YanzuoLu/CFLD#36]
![image](https://github.com/user-attachments/assets/524acbcf-10f0-4468-889d-f4af00e77175)
Hello authors, thanks for the great work. I want to know how you obtained the results in Table 2, which seem to differ from those provided in the original papers.

**Comment by YanzuoLu** [comment]
Hi @CHNxindong 
They are referenced from [NTED](https://openaccess.thecvf.com/content/CVPR2022/papers/Ren_Neural_Texture_Extraction_and_Distribution_for_Controllable_Person_Image_Synthesis_CVPR_2022_paper.pdf).

**Comment by CHNxindong** [comment]
Thanks for your response!
