### ISSUE TITLE
是否可以认为当我使用其他类型的图片不能直接得到很好的输出需要自己针对性的做训练

### ISSUE THREAD

**Issue by Thesaltedfish-single** [YanzuoLu/CFLD#38]
我目前工作希望使用一个即用的姿势转换方法。我对你们的工作做了测试，发现在提供的样例上表现不错，但是当对其他图片做直接应用时发现效果很不好。
![img_v3_02fo_9fc93416-5e08-49a8-ae85-c31867f03acg](https://github.com/user-attachments/assets/fb7cb2e3-8510-4413-ace3-243a5176ae3d)
![img_v3_02fo_35812dd8-7ee7-4e9c-8255-6aea8f96c98g](https://github.com/user-attachments/assets/83066a26-dd8c-4829-bf91-f9285d22f919)
↑为我在提供的样例上运行的结果
↓为我自己使用的图片结果，二者使用了一致的姿势fashionMENShirts_Polosid0000348912_1front.jpg
![img_v3_02fo_d826bdf5-68f7-4158-9a8d-000287ba85bg](https://github.com/user-attachments/assets/3e53520b-54e5-49d2-9076-06d3134b0812)
![img_v3_02fo_12d0d015-91a1-496b-af94-9df05ceb2d6g](https://github.com/user-attachments/assets/d5f5e970-8d8c-44ac-9838-017d1156bb16)

我发现自己使用的图片发生了性别转换
在实际测试中我已经尝试了对自己的图片做抠图和resize的预处理工作，以及没有做预处理的原图输入的尝试，都为类似的结果

**Comment by YanzuoLu** [comment]
Hi @Thesaltedfish-single 
I don't think using this work to synthesis in the wild will be a good idea since the task of PGPIS targets on the specific dataset and the base model SD15 is too weak.
I recommend you to read https://arxiv.org/pdf/2409.09593 which might help with you.
Good luck!

**Comment by Thesaltedfish-single** [comment]
> Hi @Thesaltedfish-single I don't think using this work to synthesis in the wild will be a good idea since the task of PGPIS targets on the specific dataset and the base model SD15 is too weak. I recommend you to read https://arxiv.org/pdf/2409.09593 which might help with you. Good luck!

Thanks!
