### ISSUE TITLE
why not generate 750*1024 ims like origin imgs in Deepfashion dataset?

### ISSUE THREAD

**Issue by LeonJoe13** [YanzuoLu/CFLD#5]
Thank you for your wonderful efforts in this work, I just wondering why not generate the same resolution like origin imgs in Deepfashion dataset, why choose lower resolution?

**Comment by YanzuoLu** [comment]
Thanks for your attention to our work. 
For one thing, we adopt SD1.5 so the generation is fixed on 512x512. The evaluation on different resolution is achieved by resizing.
For another thing, of course that we can achieve 1024x750 generation or different aspect ratio with SDXL. But the evaluation with other state-of-the-arts can be not fair in the paper. 
As a open-sourced project, I do think that your suggestion is reasonable to set up a new standard.
We may plan to make this happen : ) Thanks!

**Comment by LeonJoe13** [comment]
many thank for your reply, do you try train in higher resolution, does it better?

**Comment by YanzuoLu** [comment]
Sorry that we haven't give it a try.
If we want to generate higher resolution images, we might also need to increase the capacity of the feature network I guessed.
Or maybe the current 256x256 swin-transformer is also okay. 
Anyway I have no idea but to experiment with it planned in the near future. Thanks : )

**Comment by colorful-liyu** [comment]
Hello, sorry to bother you.
I have tried contacting the DeepFashion project managers to request the unzip password, but unfortunately I haven’t received any response. May I kindly ask if you would be able to share the password with me?

I am a PhD student conducting research in the field of fashion and clothing, and this dataset would be very important for my work. Thank you very much in advance for your help!

My email: melodious@sjtu.edu.cn
