### ISSUE TITLE
about Inference

### ISSUE THREAD

**Issue by ButoneDream** [YanzuoLu/CFLD#7]
how can i inference with my own local images？
![image](https://github.com/YanzuoLu/CFLD/assets/98502973/be0a3cc9-52ed-40d6-b08b-d77d1f2611d7)
it seems like test all the testdataset?

**Comment by YanzuoLu** [comment]
We have a demonstration of arbitrary pose in the supplementary materials (haven't included in our arXiv preprint), which is in line with inferencing with our own images.
I will clean it up and upload that .ipynb file later this week.

**Comment by ButoneDream** [comment]
thanks !

**Comment by YanzuoLu** [comment]
We upload the [jupyter notebook](https://github.com/YanzuoLu/CFLD/blob/main/playground.ipynb) for inference/reasoning. You could modify it as you want, e.g. replacing the conditional image with your customized one and randomly sampling a target pose from the test dataset.

**Comment by justinday123** [comment]
Is there no way to use my own target pose?
