### ISSUE TITLE
How to reason, can you directly specify a picture? I tried PCDMs and wanted to compare

### ISSUE THREAD

**Issue by StartHua** [YanzuoLu/CFLD#9]
How to reason, can you directly specify a picture? I tried PCDMs and wanted to compare

**Comment by YanzuoLu** [comment]
We upload the [jupyter notebook](https://github.com/YanzuoLu/CFLD/blob/main/playground.ipynb) for inference/reasoning. You could modify it as you want, e.g. replacing the conditional image with your customized one and randomly sampling a target pose from the test dataset.
